<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[the test suite started at : 24-06-2020 08-43-18]]>
    </line>
    <line>
      <![CDATA[Browser launched successfully ]]>
    </line>
    <line>
      <![CDATA[Application loaded ]]>
    </line>
    <line>
      <![CDATA[The test case started at : tc_0224-06-2020 08-43-30]]>
    </line>
    <line>
      <![CDATA[Clicke onAccount Button]]>
    </line>
    <line>
      <![CDATA[Entered Textanuj.lpu1@gmail.com In the Username TextBox]]>
    </line>
    <line>
      <![CDATA[Entered TextTest@123 In the password TextBox]]>
    </line>
    <line>
      <![CDATA[Clicke onLogin Btn]]>
    </line>
    <line>
      <![CDATA[The test case   tc_02Completed At :24-06-2020 08-43-37]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="20755" started-at="2020-06-24T15:13:18Z" finished-at="2020-06-24T15:13:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20755" started-at="2020-06-24T15:13:18Z" finished-at="2020-06-24T15:13:38Z">
      <class name="com.tyss.projectframeworks.scripts.LogiTest">
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:com.tyss.projectframeworks.scripts.LogiTest@31ef45e3]" name="setUp" is-config="true" duration-ms="12134" started-at="2020-06-24T20:43:18Z" finished-at="2020-06-24T20:43:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@315f43d5]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Browser launched successfully ]]>
            </line>
            <line>
              <![CDATA[Application loaded ]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tc_02()[pri:0, instance:com.tyss.projectframeworks.scripts.LogiTest@31ef45e3]" name="tc_02" duration-ms="7482" started-at="2020-06-24T20:43:30Z" finished-at="2020-06-24T20:43:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Shopping Portal | Signi-in | Signup] but found [My Cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Shopping Portal | Signi-in | Signup] but found [My Cart]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tyss.projectframeworks.scripts.LogiTest.tc_02(LogiTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The test case started at : tc_0224-06-2020 08-43-30]]>
            </line>
            <line>
              <![CDATA[Clicke onAccount Button]]>
            </line>
            <line>
              <![CDATA[Entered Textanuj.lpu1@gmail.com In the Username TextBox]]>
            </line>
            <line>
              <![CDATA[Entered TextTest@123 In the password TextBox]]>
            </line>
            <line>
              <![CDATA[Clicke onLogin Btn]]>
            </line>
            <line>
              <![CDATA[The test case   tc_02Completed At :24-06-2020 08-43-37]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc_02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tyss.projectframeworks.scripts.LogiTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="204" started-at="2020-06-24T20:43:38Z" finished-at="2020-06-24T20:43:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tyss.projectframeworks.scripts.LogiTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
